config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  post '/callback', to: 'linebot#callback'

  root 'static_pages#top'

  get 'contact', to: 'static_pages#contact'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  resources :users, only: [:new]
  resources :homes, only: [:index]
  resources :charges
  resources :games
  resources :budgets
  resources :gachas
  resources :stones

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :charges

    validates :year, presence: true
    validates :month, presence: true
    validates :amount, presence: true
end

app/models/charge.rb
class Charge < ApplicationRecord
    belongs_to :user
    belongs_to :game
    belongs_to :budget, optional: true
  
    validates :game_id, presence: true
    validates :amount, presence: true, numericality: { greater_than: 0 }
    validates :date, presence: true

    mount_uploader :image, ImageUploader

    def self.ransackable_attributes(auth_object = nil)
        ["amount", "budget_id", "created_at", "date", "game_id", "image", "memo", "updated_at", "user_id"]
    end
end
  

app/models/gacha.rb
class Gacha < ApplicationRecord
    belongs_to :user
    belongs_to :game

    validates :number, presence: true
    validates :date, presence: true

    mount_uploader :image, ImageUploader

end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    has_many :gachas
    has_many :charges
    has_many :stones

    validates :name, presence: true
end

app/models/stone.rb
class Stone < ApplicationRecord
    belongs_to :user
    belongs_to :game
  
    # 目標のガチャ石の数に到達するまでの日数を計算するメソッド
    def days_to_reach_goal
      daily_total_stones = login + daily
      remaining_stones = goal - current

      # 最終更新日から現在までの経過日数を計算
      elapsed_days = (Time.zone.now.to_date - updated_at.to_date).to_i
      days = 0

      # 経過日数分、remaining_stonesを減算
      elapsed_days.times do |day|
        remaining_stones -= daily_total_stones
      end
  
      while remaining_stones > 0
        days += 1
        remaining_stones -= daily_total_stones
      end
  
      days
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]

  has_many :charges
  has_many :games
  has_many :gachas
  has_many :stones
  
  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!

    def index
        @games = current_user.games
    end
    
    def new
        @game = Game.new
    end
    
    def create
        @game = current_user.games.new(game_params)
        if @game.save
          redirect_to games_path, success: '登録しました'
        else
          flash.now[:danger] = '登録できませんでした'
          render :new
        end
    end

    def show
        @game = Game.find(params[:id])
    end

    def edit
        @game = current_user.games.find(params[:id])
    end

    def update
        @game = current_user.games.find(params[:id])
        if @game.update(game_params)
          redirect_to game_path, success: '記録を更新しました'
        else
          flash.now[:danger] = '記録を更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        @game = Game.find(params[:id])
        @game.destroy!
        redirect_to games_path, success: '記録を削除しました'
    end
    
    private
    
     def game_params
        params.require(:game).permit(:user_id, :name)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    current_year = Time.current.year
    current_month = Time.current.month
    @budget = Budget.where(year: current_year, month: current_month).first
    @charges_this_month = Charge.where("date >= ? AND date <= ?", Time.current.beginning_of_month, Time.current.end_of_month).order(:date)
    @total_spent_this_month = @charges_this_month.sum(:amount)
    @remaining_budget = @budget.amount - @total_spent_this_month if @budget
    @charges_last_month = Charge.where("date >= ? AND date <= ?", Time.current.last_month.beginning_of_month, Time.current.last_month.end_of_month)
    @total_spent_last_month = @charges_last_month.sum(:amount)
    @difference_from_last_month = @total_spent_this_month - @total_spent_last_month
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end

  def contact; end
  def privacy_policy; end
  def terms_of_service; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          # サインアップ後、ユーザーをログインさせる(オプション)
          sign_in(@user)
          # サインアップ後のリダイレクト先
          redirect_to new_user_sessions_path, flash[:notice] =  '登録されました'
        else
          render :new
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/gachas_helper.rb
module GachasHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stones_helper.rb
module StonesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/contact.html.erb
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSc5iCxi9Yzu2PU9TBlIBWsEybAgj0YKP3TPS26kN7MFxffEMg/viewform?embedded=true" width="100%" height="585" frameborder="0" marginheight="0" marginwidth="0">読み込んでいます…</iframe>

app/views/static_pages/privacy_policy.html.erb
<div class="text-gray-700">
  <div class="main_image p-4 sm:p-10">
  <p class="text-2xl sm:text-4xl text-center py-5 sm:py-10 font-bold text-stone-600">プライバシーポリシー</p>
      <div class="text-gray-700">
        <div class="p-4 sm:p-6">
          <div class="bg-white rounded-lg shadow-md px-5 sm:px-10 py-5 sm:py-10">
          <p class="text-xl sm:text-2xl mt-4 sm:mt-6">お客様から取得する情報</p>
          <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様から以下の情報を取得します。</p>
          <ul class="mt-3 sm:mt-6 space-y-2 pl-5 sm:pl-20 list-disc text-sm sm:text-base">
              <li>写真や動画</li>
              <li>外部サービスでお客様が利用するID、その他外部サービスのプライバシー設定によりお客様が連携先に開示を認めた情報</li>
              <li>Cookie(クッキー)を用いて生成された識別情報</li>
              <li>OSが生成するID、端末の種類、端末識別子等のお客様が利用するOSや端末に関する情報</li>
              <li>当ウェブサイトの滞在時間、入力履歴、購買履歴等の当ウェブサイトにおけるお客様の行動履歴</li>
              <li>お客様の位置情報</li>
              <li>当アプリの起動時間、入力履歴、購買履歴等の当アプリの利用履歴</li>
            </ul>
            <br>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">お客様の情報を利用する目的</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様から取得した情報を、以下の目的のために利用します。</p>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">
            <ul class="mt-3 sm:mt-6 space-y-2 pl-5 sm:pl-20 list-disc text-sm sm:text-base">
              <li>当サービスに関する登録の受付、お客様の本人確認、認証のため</li>
              <li>お客様の当サービスの利用履歴を管理するため</li>
              <li>当サービスにおけるお客様の行動履歴を分析し、当サービスの維持改善に役立てるため</li>
              <li>お客様からのお問い合わせに対応するため</li>
              <li>当方の規約や法令に違反する行為に対応するため</li>
              <li>当サービスの変更、提供中止、終了、契約解除をご連絡するため</li>
              <li>当規約の変更等を通知するため</li>
              <li>以上の他、当サービスの提供、維持、保護及び改善のため</li>
            </ul>
            <br>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">安全管理のために講じた措置</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方が、お客様から取得した情報に関して安全管理のために講じた措置につきましては、末尾記載のお問い合わせ先にご連絡をいただきましたら、法令の定めに従い個別にご回答させていただきます。</p>
            <br>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">第三者提供</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様から取得する情報のうち、個人データ（個人情報保護法第１６条第３項）に該当するものついては、あらかじめお客様の同意を得ずに、第三者（日本国外にある者を含みます。）に提供しません。</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">但し、次の場合は除きます。</p>
            <ul class="mt-3 sm:mt-6 space-y-2 pl-5 sm:pl-20 list-disc text-sm sm:text-base">
              <li>個人データの取扱いを外部に委託する場合</li>
              <li>当方や当サービスが買収された場合</li>
              <li>事業パートナーと共同利用する場合（具体的な共同利用がある場合は、その内容を別途公表します。）</li>
              <li>その他、法律によって合法的に第三者提供が許されている場合</li>
            </ul>
            <br>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">アクセス解析ツール</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、お客様のアクセス解析のために、「Googleアナリティクス」を利用しています。<br>
              Googleアナリティクスは、トラフィックデータの収集のためにCookieを使用しています。<br>
              トラフィックデータは匿名で収集されており、個人を特定するものではありません。<br>
              Cookieを無効にすれば、これらの情報の収集を拒否することができます。<br>
              詳しくはお使いのブラウザの設定をご確認ください。<br>
              Googleアナリティクスについて、詳しくはGoogleアナリティクスにてご確認ください。</p>
            <br>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">プライバシーポリシーの変更</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">当方は、必要に応じて、このプライバシーポリシーの内容を変更します。<br>
              この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。</p>
            <br>
            <p class="text-xl sm:text-2xl mt-4 sm:mt-6">お問い合わせ</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">お客様の情報の開示、情報の訂正、利用停止、削除をご希望の場合は、以下のメールアドレスにご連絡ください。</p>
            <p class="pl-10 mt-3" style="word-break: break-all;">claruslapis@gmail.com</p>
            <p class="mt-2 sm:mt-3 pl-5 sm:pl-10">この場合、必ず、運転免許証のご提示等当方が指定する方法により、ご本人からのご請求であることの確認をさせていただきます。<br>
              なお、情報の開示請求については、開示の有無に関わらず、ご申請時に一件あたり1,000円の事務手数料を申し受けます。</p>
            <br>
            <p class="text-center mt-5 sm:mt-10 text-sm sm:text-base">2024年3月10日 制定</p>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/top.html.erb
<div class="mx-auto w-11/12 text-center max-w-lg">
  <div class="my-20">
    <h1 class="text-lg font-bold my-4 border-dotted border-b-4 border-green-200">課金やガチャの記録を一括で管理しよう！</h1>
    <p class="text-left sm:text-center leading-8 w-11/12 mx-auto">
      KAKINkanriは、課金記録やガチャの結果を登録したり、どれだけの期間ガチャ禁すれば目標のガチャ石が貯まるのかを確認したりすることができるWebアプリです
    </p>
  </div>
  <div class="my-20">
    <h1 class="text-lg font-bold my-4 border-dotted border-b-4 border-green-200">使い方はとても簡単！</h1>
    <p class="text-left sm:text-center leading-8 w-11/12 mx-auto">
      まずは、今月の予算を登録しましょう。その後、課金を登録することによって、今月の残り予算が表示されるようになります。課金のしすぎにはご注意を！
    </p>
    <p class="text-left sm:text-center leading-8 w-11/12 mx-auto">
      公式LINEアカウントで「課金可能額」と送信すると今月の使用可能額が返信されます。ぜひ活用してみてください。
    </p>
  </div>
  <div class="my-20">
    <% if user_signed_in? %>
        <h1 class="text-lg font-bold my-4 border-dotted border-b-4 border-green-200">予算登録はこちらから！</h1>
        <%= link_to '予算登録', new_budget_path, class: "btn btn-primary shadow-xl mt-10" %>
    <% else %>
        <h1 class="text-lg font-bold my-4 border-dotted border-b-4 border-green-200">登録はこちらから！</h1>
            <%= button_to omniauth_authorize_path(:user, :line), data: { turbo: false } do %>
                <%= image_tag("btn_login_base.png") %>
            <% end %>
    <% end %>
  </div> 

</div>