config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  post '/callback', to: 'linebot#callback'

  root 'static_pages#top'

  get 'contact', to: 'static_pages#contact'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  resources :users, only: [:new]
  resources :homes, only: [:index]
  resources :charges
  resources :games
  resources :budgets
  resources :gachas
  resources :stones

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :charges

    validates :year, presence: true
    validates :month, presence: true
    validates :amount, presence: true
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
    before_action :authenticate_user!

    def index
        @budgets = Budget.order(year: :asc, month: :asc)
    end
    
    def new
        @budget = Budget.new
    end
    
    def create
        @budget = Budget.new(budget_params)
        # すでに同じ年月が存在するかどうかをチェック
        existing_budget = Budget.find_by(year: @budget.year, month: @budget.month)
        if existing_budget
            flash.now[:danger] = "#{existing_budget.year}年#{existing_budget.month}月はすでに登録されています"
            render :new
            return
        end
        if @budget.save
          redirect_to budgets_path, success: '登録しました'
        else
          flash.now[:danger] = '登録できませんでした'
          render :new
        end
    end

    def show
        @budget = Budget.find(params[:id])
    end

    def edit
        @budget = Budget.find(params[:id])
    end

    def update
        @budget = Budget.find(params[:id])
        existing_budget = Budget.find_by(year: @budget.year, month: @budget.month)
        if existing_budget
            flash.now[:danger] = "#{existing_budget.year}年#{existing_budget.month}月はすでに登録されています"
            render :new
            return
        end
        if @budget.update(budget_params)
          redirect_to budgets_path, success: '予算を更新しました'
        else
          flash.now[:danger] = '予算を更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        @budget = Budget.find(params[:id])
        @budget.destroy!
        redirect_to budgets_path, success: '予算を削除しました'
    end
    
    private
    
    def budget_params
        params.require(:budget).permit(:year, :month, :amount)
    end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/views/budgets/_form.html.erb
<%= form_with model: budget, local: true, class: "space-y-5" do |f| %>
    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">年 ※必須</span>
      </div>
      <%= f.select :year, (2000..Date.today.year).to_a.reverse, { prompt: '年を選択' }, class: 'select select-bordered w-full max-w-xs' %>
    </label>
    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">月 ※必須</span>
      </div>
      <%= f.select :month, (1..12).to_a, { prompt: '月を選択' }, class: 'select select-bordered w-full max-w-xs' %>
    </label>
    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">予算 ※必須</span>
      </div>
      <%= f.text_field :amount, placeholder: "¥", class: "input input-bordered w-full max-w-xs" %>
    </label>
    
    <%= f.submit "登録", class: 'btn btn-primary'  %>
<% end %>

app/views/budgets/edit.html.erb
<div class="container flex justify-center items-center min-h-screen">
  <div class="card">
    <div class="card-header mx-auto w-5/6 max-w-lg text-center my-10">
      <h1 class="mb-4 text-2xl font-bold">予算編集</h1>
    </div>
    <div class="card-body">
      <%= render 'form', budget: @budget %>
    </div>
  </div>
</div>

app/views/budgets/index.html.erb
<div class="mx-auto w-11/12 max-w-lg text-center my-10">
    <div class="flex justify-between mb-4">
        <h1 class="text-2xl font-bold">登録済み予算一覧</h1>
        <%= link_to "NEW", new_budget_path, class: "link link-hover" %>
    </div>
    <div class="overflow-x-auto">
        <table class="table">
            <tbody>
                <% @budgets.each do |budget| %>
                    <tr>
                        <td><%= budget.year %>/<%= budget.month %></td>
                       <td><%= budget.amount %>円</td>
                        <td><%= link_to '編集', edit_budget_path(budget), class: 'btn btn-accent btn-sm' %></td>
                        <td><%= link_to '削除',
                            budget_path(budget),
                            class: 'btn btn-secondary btn-sm',
                            data: { turbo_method: :delete} %></td>

                    </tr>
                <% end %>
             </tbody>
        </table>
    </div>
</div>

app/views/budgets/new.html.erb
<div class="container flex justify-center items-center min-h-screen">
  <div class="card">
    <div class="card-header mx-auto w-5/6 max-w-lg text-center my-10">
      <h1 class="mb-4 text-2xl font-bold">予算登録</h1>
    </div>
    <div class="card-body">
      <%= render 'form', budget: @budget %>
    </div>
  </div>
</div>