config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  post '/callback', to: 'linebot#callback'

  root 'static_pages#top'

  get 'contact', to: 'static_pages#contact'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  resources :users, only: [:new]
  resources :homes, only: [:index]
  resources :charges
  resources :games
  resources :budgets
  resources :gachas
  resources :stones

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/gacha.rb
class Gacha < ApplicationRecord
    belongs_to :user
    belongs_to :game

    validates :number, presence: true
    validates :date, presence: true

    mount_uploader :image, ImageUploader

end

app/controllers/gachas_controller.rb
class GachasController < ApplicationController
    before_action :authenticate_user!

    def index
        @gachas = current_user.gachas
    end
    
    def new
        @gacha = Gacha.new
        @games = current_user.games
    end
    
    def create
        @gacha = current_user.gachas.new(gacha_params)
        if @gacha.save
          redirect_to gachas_path, success: '登録しました'
        else
          @games = current_user.games
          flash.now[:danger] = '登録できませんでした'
          render :new
        end
    end

    def show
        @gacha = Gacha.find(params[:id])
    end

    def edit
        @gacha = Gacha.find(params[:id])
        @games = current_user.games
    end

    def update
        @gacha = current_user.gachas.find(params[:id])
        if @gacha.update(gacha_params)
          redirect_to gachas_path, success: '記録を更新しました'
        else
          @games = current_user.games
          flash.now[:danger] = '記録を更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        @gacha = Gacha.find(params[:id])
        @gacha.destroy!
        redirect_to gachas_path, success: '予算を削除しました'
    end
    
    private
    
    def gacha_params
        params.require(:gacha).permit(:user_id, :game_id, :amount, :number, :date, :image, :memo)
    end
end

app/helpers/gachas_helper.rb
module GachasHelper
end

app/views/gachas/_form.html.erb
<%= form_with model: gacha, local: true, class: "space-y-5" do |f| %>

    <label class="form-control w-full max-w-xs">
        <div class="label">
            <span class="label-text">ガチャ日 ※必須</span>
        </div>
        <%= f.date_field :date, class: "input input-bordered w-full max-w-xs" %>
    </label>

    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">ゲーム名 ※必須</span>
      </div>
      <%= f.collection_select :game_id, @games, :id, :name, { include_blank: '登録済ゲーム名から選択' }, { class: 'select select-bordered  w-full max-w-xs' } %>
    </label>

    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">回数 ※必須</span>
      </div>
      <%= f.text_field :number, placeholder: "連", class: "input input-bordered w-full max-w-xs" %>
    </label>

    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">課金額</span>
      </div>
      <%= f.text_field :amount, placeholder: "¥", class: "input input-bordered w-full max-w-xs" %>
    </label>
  
    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">画像</span>
      </div>
      <%= f.file_field :image, class: 'file-input file-input-bordered file-input-accent w-full max-w-xs' %>
    </label>
  
    <label class="form-control w-full max-w-xs">
      <div class="label">
        <span class="label-text">メモ</span>
      </div>
      <%= f.text_area :memo, class: 'textarea textarea-bordered h-24 w-full' %>
    </label>
    
    <%= f.submit "登録", class: 'btn btn-primary' %>
  <% end %>

app/views/gachas/edit.html.erb
<div class="container flex justify-center items-center min-h-screen">
  <div class="card">
    <div class="card-header mx-auto w-5/6 max-w-lg text-center my-10">
      <h1 class="mb-4 text-2xl font-bold">ガチャ記録編集</h1>
    </div>
    <div class="card-body">
      <%= render 'form', gacha: @gacha %>
    </div>
  </div>
</div>

app/views/gachas/index.html.erb
<div class="mx-auto w-11/12 max-w-lg text-center my-10">
    <div class="flex justify-between mb-4">
        <h1 class="mb-4 text-2xl font-bold">ガチャ記録一覧</h1>
        <%= link_to "NEW", new_gacha_path, class: "link link-hover" %>
    </div>
    <div class="overflow-x-auto">
        <table class="table">
            <tbody>
                <% @gachas.each do |gacha| %>
                    <tr>
                        <td><%= gacha.date.strftime('%m/%d') %></td>
                        <td><%= gacha.game.name %></td>
                        <td><%= gacha.number %>連</td>
                        <td><%= gacha.amount %>円</td>
                        <td><%= link_to '詳細', gacha_path(gacha), class: 'btn btn-neutral btn-sm' %></td>
                        <td><%= link_to '編集', edit_gacha_path(gacha), class: 'btn btn-accent btn-sm' %></td>
                        <td><%= link_to '削除',
                              gacha_path(gacha),
                              class: 'btn btn-secondary btn-sm',
                              data: { turbo_method: :delete} %></td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

app/views/gachas/new.html.erb
<div class="container flex justify-center items-center min-h-screen">
  <div class="card">
    <div class="card-header mx-auto w-5/6 max-w-lg text-center my-10">
      <h1 class="mb-4 text-2xl font-bold">ガチャ結果登録</h1>
    </div>
    <div class="card-body">
      <%= render 'form', gacha: @gacha %>
    </div>
  </div>
</div>

app/views/gachas/show.html.erb
<div class="mx-auto w-11/12 max-w-lg text-center my-10">
  <h1 class="mb-4 text-2xl font-bold">詳細内容</h1>
    <div class="text-end">
      <%= link_to '編集', edit_gacha_path(@gacha), class: 'btn btn-accent btn-sm' %>
      <%= link_to '削除',
              gacha_path(@gacha),
              class: 'btn btn-secondary btn-sm',
              data:  { turbo_method: :delete } %>
    </div>
  <div class="overflow-x-auto">
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Game</th>
                    <th>Number</th>
                    <th>Amount</th>
                    <th>Memo</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= @gacha.date.strftime('%m/%d') %></td>
                <td><%= @gacha.game.name %></td>
                <td><%= @gacha.number %>連</td>
                <td><%= @gacha.amount %>円</td>
                <td><%= @gacha.memo %></td>
                <td><%= image_tag(@gacha.image.url) if @gacha.image.present? %></td>
              </tr>
            </tbody>
        </table>
  </div>
</div>