config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks"
  }

  post '/callback', to: 'linebot#callback'

  root 'static_pages#top'

  get 'contact', to: 'static_pages#contact'
  get 'privacy_policy', to: 'static_pages#privacy_policy'
  get 'terms_of_service', to: 'static_pages#terms_of_service'

  resources :users, only: [:new]
  resources :homes, only: [:index]
  resources :charges
  resources :games
  resources :budgets
  resources :gachas
  resources :stones

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/budget.rb
class Budget < ApplicationRecord
    has_many :charges

    validates :year, presence: true
    validates :month, presence: true
    validates :amount, presence: true
end

app/models/charge.rb
class Charge < ApplicationRecord
    belongs_to :user
    belongs_to :game
    belongs_to :budget, optional: true
  
    validates :game_id, presence: true
    validates :amount, presence: true, numericality: { greater_than: 0 }
    validates :date, presence: true

    mount_uploader :image, ImageUploader

    def self.ransackable_attributes(auth_object = nil)
        ["amount", "budget_id", "created_at", "date", "game_id", "image", "memo", "updated_at", "user_id"]
    end
end
  

app/models/gacha.rb
class Gacha < ApplicationRecord
    belongs_to :user
    belongs_to :game

    validates :number, presence: true
    validates :date, presence: true

    mount_uploader :image, ImageUploader

end

app/models/game.rb
class Game < ApplicationRecord
    belongs_to :user
    has_many :gachas
    has_many :charges
    has_many :stones

    validates :name, presence: true
end

app/models/stone.rb
class Stone < ApplicationRecord
    belongs_to :user
    belongs_to :game
  
    # 目標のガチャ石の数に到達するまでの日数を計算するメソッド
    def days_to_reach_goal
      daily_total_stones = login + daily
      remaining_stones = goal - current

      # 最終更新日から現在までの経過日数を計算
      elapsed_days = (Time.zone.now.to_date - updated_at.to_date).to_i
      days = 0

      # 経過日数分、remaining_stonesを減算
      elapsed_days.times do |day|
        remaining_stones -= daily_total_stones
      end
  
      while remaining_stones > 0
        days += 1
        remaining_stones -= daily_total_stones
      end
  
      days
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[line]

  has_many :charges
  has_many :games
  has_many :gachas
  has_many :stones
  
  def social_profile(provider)
    social_profiles.select { |sp| sp.provider == provider.to_s }.first
  end

  def set_values(omniauth)
    return if provider.to_s != omniauth["provider"].to_s || uid != omniauth["uid"]
    credentials = omniauth["credentials"]
    info = omniauth["info"]

    access_token = credentials["refresh_token"]
    access_secret = credentials["secret"]
    credentials = credentials.to_json
    name = info["name"]
    # self.set_values_by_raw_info(omniauth['extra']['raw_info'])
  end

  def set_values_by_raw_info(raw_info)
    self.raw_info = raw_info.to_json
    self.save!
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :authenticate_user!

    def index
        @games = current_user.games
    end
    
    def new
        @game = Game.new
    end
    
    def create
        @game = current_user.games.new(game_params)
        if @game.save
          redirect_to games_path, success: '登録しました'
        else
          flash.now[:danger] = '登録できませんでした'
          render :new
        end
    end

    def show
        @game = Game.find(params[:id])
    end

    def edit
        @game = current_user.games.find(params[:id])
    end

    def update
        @game = current_user.games.find(params[:id])
        if @game.update(game_params)
          redirect_to game_path, success: '記録を更新しました'
        else
          flash.now[:danger] = '記録を更新できませんでした'
          render :edit
        end
    end
    
    def destroy
        @game = Game.find(params[:id])
        @game.destroy!
        redirect_to games_path, success: '記録を削除しました'
    end
    
    private
    
     def game_params
        params.require(:game).permit(:user_id, :name)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    current_year = Time.current.year
    current_month = Time.current.month
    @budget = Budget.where(year: current_year, month: current_month).first
    @charges_this_month = Charge.where("date >= ? AND date <= ?", Time.current.beginning_of_month, Time.current.end_of_month).order(:date)
    @total_spent_this_month = @charges_this_month.sum(:amount)
    @remaining_budget = @budget.amount - @total_spent_this_month if @budget
    @charges_last_month = Charge.where("date >= ? AND date <= ?", Time.current.last_month.beginning_of_month, Time.current.last_month.end_of_month)
    @total_spent_last_month = @charges_last_month.sum(:amount)
    @difference_from_last_month = @total_spent_this_month - @total_spent_last_month
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end
    
    def create
        @user = User.new(user_params)
        if @user.save
          # サインアップ後、ユーザーをログインさせる(オプション)
          sign_in(@user)
          # サインアップ後のリダイレクト先
          redirect_to new_user_sessions_path, flash[:notice] =  '登録されました'
        else
          render :new
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/gachas_helper.rb
module GachasHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/linebot_helper.rb
module LinebotHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/stones_helper.rb
module StonesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="pastel">
  <head>
    <title>KAKINkanri</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= render 'shared/flash_message' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center p-10 bg-gradient-to-br from-blue-100 to-green-100 text-base-content rounded">
  <div class="flex flex-col items-center">
    <nav class="flex flex-wrap justify-center gap-x-10 gap-y-6 md:justify-start md:gap-10">
      <%= link_to "お問い合わせ", contact_path, class: "duration-100 hover:text-indigo-300" %>
      <%= link_to "利用規約", terms_of_service_path, class: "duration-100 hover:text-indigo-300" %>
      <%= link_to "プライバシーポリシー", privacy_policy_path , class: "duration-100 hover:text-indigo-300" %>
    </nav>  
  </div>
  <aside>
    <p>Copyright © KAKINkanri</p>
  </aside>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="drawer drawer-end">
    <input id="my-drawer-3" type="checkbox" class="drawer-toggle" /> 
    <div class="drawer-content flex flex-col">

      <div class="w-full navbar bg-gradient-to-bl from-blue-100 to-green-100">

      <div class="flex-1 px-2 mx-2">
        <%= link_to "KAKINkanri", root_path, class: "pt-2 font-bold text-2xl hover:opacity-70 mt-[-7px]" %>
      </div>
        <% if user_signed_in? %>
          <div class="flex-none lg:hidden">
            <label for="my-drawer-3" aria-label="open sidebar" class="btn btn-square btn-ghost">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
            </label>
          </div> 
        <% end %>

        <div class="flex-none hidden lg:block">
          <div class="flex items-center justify-center w-100">
            <ul class="menu menu-horizontal">
              <% if user_signed_in? %>
                <%= link_to "ホーム", homes_path, class: "link-hover mx-2" %>
                <%= link_to "課金記録一覧", charges_path, class: "ink-hover mx-2" %>
                <%= link_to "課金記録作成", new_charge_path, class: "link-hover mx-2" %>
                <%= link_to "ゲーム名一覧", games_path, class: "link-hover mx-2" %>
                <%= link_to "予算登録一覧", budgets_path, class: "link-hover mx-2" %>
                <%= link_to "ガチャ記録一覧", gachas_path, class: "link-hover mx-2" %>
                <%= link_to "ガチャ石日数", stones_path, class: "link-hover mx-2" %>
                <%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "link-hover mx-2" %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <% if user_signed_in? %>
      <div class="drawer-side z-10">
        <label for="my-drawer-3" aria-label="close sidebar" class="drawer-overlay"></label> 
        <div class="menu p-4 w-60 min-h-full bg-green-50">
          <li><%= link_to "ホーム", homes_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "課金記録一覧", charges_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "課金記録作成", new_charge_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "ゲーム名一覧", games_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "予算登録一覧", budgets_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "ガチャ記録一覧", gachas_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "ガチャ石日数", stones_path, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, data: { turbo_method: :delete }, class: "block px-4 py-2 my-1 hover rounded-full" %></li>
        </div> 
      </div>
    <% end %>
  </div>
</header>